Vagrant.configure("2") do |config|
  config.vm.hostname = "gwdg-docker-host"
  config.vm.box_check_update = false

  config.ssh.password  = "tcuser" 
  config.ssh.insert_key = true

  config.vm.box = "hashicorp/boot2docker"

  #config.vm.network "forwarded_port", guest: 8080, host: 8080
end
