Vagrant.configure("2") do |config|
  config.vm.hostname = "mikelangelo-docker-host"
  config.vm.box_check_update = false

  config.vm.box = "hashicorp/boot2docker"

  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "forwarded_port", guest: 29418, host: 29418
  config.vm.network "forwarded_port", guest: 8081, host: 8081
end